import pytz
from cachetools import TTLCache

TZ = pytz.timezone("Australia/Brisbane")

alternative_labels = {
    "CPI (YoY)": {
        "label": "Unemployment Claims",
        "condition": "stop",
    },
    "Unemployment Claims": {
        "label": "CPI (YoY)",
        "condition": "stop",
    },
}

alternative_conditional_labels = {
    "Employment Change": [
        {
            "alt": {
                "label": "Unemployment Rate",
                "condition": "below",
            },
            "condition": "above",
        },
        {
            "alt": {
                "label": "Unemployment Rate",
                "condition": "above",
            },
            "condition": "below",
        },
    ],
    "Unemployment Rate": [
        {
            "alt": {
                "label": "Employment Change",
                "condition": "above",
            },
            "condition": "below",
        },
        {
            "alt": {
                "label": "Employment Change",
                "condition": "below",
            },
            "condition": "above",
        },
    ],
}

crypto_cid = []
wait_for_result = TTLCache(maxsize=100, ttl=60 * 60)  # 1 hour
forex_cid = [1248259151788904521]
cid = forex_cid + crypto_cid

no_dc_trade_channel = 1181911448943857744
no_tg_trade_channel = -1002035778514

LOGO_BLACK = "https://telegra.ph/file/751b6b0f37a85875f5f70.jpg"
LOGO_WHITE = "https://telegra.ph/file/7d82b2aefcab691115c77.jpg"

CURRENCY_EMOJI = {
    "AED": "🇦🇪",
    "AFN": "🇦🇫",
    "ALL": "🇦🇱",
    "AMD": "🇦🇲",
    "ANG": "🇳🇱",
    "AOA": "🇦🇴",
    "ARS": "🇦🇷",
    "AUD": "🇦🇺",
    "AWG": "🇦🇼",
    "AZN": "🇦🇿",
    "BAM": "🇧🇦",
    "BBD": "🇧🇧",
    "BDT": "🇧🇩",
    "BGN": "🇧🇬",
    "BHD": "🇧🇭",
    "BIF": "🇧🇮",
    "BMD": "🇧🇲",
    "BND": "🇧🇳",
    "BOB": "🇧🇴",
    "BRL": "🇧🇷",
    "BSD": "🇧🇸",
    "BTN": "🇧🇹",
    "BWP": "🇧🇼",
    "BYN": "🇧🇾",
    "BZD": "🇧🇿",
    "CAD": "🇨🇦",
    "CDF": "🇨🇩",
    "CHF": "🇨🇭",
    "CLP": "🇨🇱",
    "CNY": "🇨🇳",
    "COP": "🇨🇴",
    "CRC": "🇨🇷",
    "CUP": "🇨🇺",
    "CVE": "🇨🇻",
    "CZK": "🇨🇿",
    "DJF": "🇩🇯",
    "DKK": "🇩🇰",
    "DOP": "🇩🇴",
    "DZD": "🇩🇿",
    "EGP": "🇪🇬",
    "ERN": "🇪🇷",
    "ETB": "🇪🇹",
    "EUR": "🇪🇺",
    "FJD": "🇫🇯",
    "FKP": "🇫🇰",
    "FOK": "🇫🇴",
    "GBP": "🇬🇧",
    "GEL": "🇬🇪",
    "GGP": "🇬🇬",
    "GHS": "🇬🇭",
    "GIP": "🇬🇮",
    "GMD": "🇬🇲",
    "GNF": "🇬🇳",
    "GTQ": "🇬🇹",
    "GYD": "🇬🇾",
    "HKD": "🇭🇰",
    "HNL": "🇭🇳",
    "HRK": "🇭🇷",
    "HTG": "🇭🇹",
    "HUF": "🇭🇺",
    "IDR": "🇮🇩",
    "ILS": "🇮🇱",
    "IMP": "🇮🇲",
    "INR": "🇮🇳",
    "IQD": "🇮🇶",
    "IRR": "🇮🇷",
    "ISK": "🇮🇸",
    "JEP": "🇯🇪",
    "JMD": "🇯🇲",
    "JOD": "🇯🇴",
    "JPY": "🇯🇵",
    "KES": "🇰🇪",
    "KGS": "🇰🇬",
    "KHR": "🇰🇭",
    "KID": "🇰🇮",
    "KMF": "🇰🇲",
    "KRW": "🇰🇷",
    "KWD": "🇰🇼",
    "KYD": "🇰🇾",
    "KZT": "🇰🇿",
    "LAK": "🇱🇦",
    "LBP": "🇱🇧",
    "LKR": "🇱🇰",
    "LRD": "🇱🇷",
    "LSL": "🇱🇸",
    "LYD": "🇱🇾",
    "MAD": "🇲🇦",
    "MDL": "🇲🇩",
    "MGA": "🇲🇬",
    "MKD": "🇲🇰",
    "MMK": "🇲🇲",
    "MNT": "🇲🇳",
    "MOP": "🇲🇴",
    "MRU": "🇲🇷",
    "MUR": "🇲🇺",
    "MVR": "🇲🇻",
    "MWK": "🇲🇼",
    "MXN": "🇲🇽",
    "MYR": "🇲🇾",
    "MZN": "🇲🇿",
    "NAD": "🇳🇦",
    "NGN": "🇳🇬",
    "NIO": "🇳🇮",
    "NOK": "🇳🇴",
    "NPR": "🇳🇵",
    "NZD": "🇳🇿",
    "OMR": "🇴🇲",
    "PAB": "🇵🇦",
    "PEN": "🇵🇪",
    "PGK": "🇵🇬",
    "PHP": "🇵🇭",
    "PKR": "🇵🇰",
    "PLN": "🇵🇱",
    "PYG": "🇵🇾",
    "QAR": "🇶🇦",
    "RON": "🇷🇴",
    "RSD": "🇷🇸",
    "RUB": "🇷🇺",
    "RWF": "🇷🇼",
    "SAR": "🇸🇦",
    "SBD": "🇸🇧",
    "SCR": "🇸🇨",
    "SDG": "🇸🇩",
    "SEK": "🇸🇪",
    "SGD": "🇸🇬",
    "SHP": "🇸🇭",
    "SLE": "🇸🇱",
    "SLL": "🇸🇱",
    "SOS": "🇸🇴",
    "SRD": "🇸🇷",
    "SSP": "🇸🇸",
    "STN": "🇸🇹",
    "SYP": "🇸🇾",
    "SZL": "🇸🇿",
    "THB": "🇹🇭",
    "TJS": "🇹🇯",
    "TMT": "🇹🇲",
    "TND": "🇹🇳",
    "TOP": "🇹🇴",
    "TRY": "🇹🇷",
    "TTD": "🇹🇹",
    "TVD": "🇹🇻",
    "TWD": "🇹🇼",
    "TZS": "🇹🇿",
    "UAH": "🇺🇦",
    "UGX": "🇺🇬",
    "USD": "🇺🇸",
    "UYU": "🇺🇾",
    "UZS": "🇺🇿",
    "VES": "🇻🇪",
    "VND": "🇻🇳",
    "VUV": "🇻🇺",
    "WST": "🇼🇸",
    "XAF": "🇨🇲",
    "XCD": "🇦🇬",
    "XOF": "🇨🇮",
    "XPF": "🇵🇫",
    "YER": "🇾🇪",
    "ZAR": "🇿🇦",
    "ZMW": "🇿🇲",
    "ZWL": "🇿🇼",
}
